// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddMessage(arg1:main.User,arg2:string,arg3:string,arg4:number):Promise<void>;

export function GetMessages():Promise<Array<main.Message>>;

export function GetUsersCount():Promise<number>;
